'use client';

import{useEffect,useState}from'react';
import{useRouter}from'next/navigation';
import{getOrCreateDeviceToken}from'@/lib/device/token';
import{briefRows}from'@/lib/ui/format';
import{LoadingOverlay,SkeletonBlock}from'@/components/ui/LoadingStates';
import{Toast}from'@/components/ui/Toast';
import{CreationSettingsControls}from'@/components/ui/CreationSettingsControls';
import{NeramitIcon}from'@/components/ui/NeramitIcon';
import{normalizeCreationSettings,settingsPatch,type CreationSettings}from'@/lib/ui/creation-settings';

type Review={draft:{brief:Record<string,unknown>;title?:string};references:Array<{id:string;analysis:unknown}>};

export default function ReviewClient({draftId}:{draftId:string}){
  const[data,setData]=useState<Review|null>(null);const[busy,setBusy]=useState(false);const[settings,setSettings]=useState<CreationSettings>(()=>normalizeCreationSettings({}));const[error,setError]=useState('');const router=useRouter();
  useEffect(()=>{fetch(`/api/review?draft=${draftId}`,{headers:{'x-neramit-device':getOrCreateDeviceToken()}}).then(r=>r.json()).then(x=>{setData(x);if(x.draft?.brief)setSettings(normalizeCreationSettings(x.draft.brief));}).catch(()=>setError('โหลดข้อมูลไม่สำเร็จ'));},[draftId]);
  async function changeSettings(next:CreationSettings){setSettings(next);if(!data?.draft)return;const brief={...data.draft.brief,...settingsPatch(next)};setData({...data,draft:{...data.draft,brief}});try{await fetch(`/api/drafts/${draftId}`,{method:'PATCH',headers:{'content-type':'application/json','x-neramit-device':getOrCreateDeviceToken()},body:JSON.stringify({brief})});}catch{}}
  async function generate(){setBusy(true);setError('');try{const requestId=crypto.randomUUID();const r=await fetch('/api/generate',{method:'POST',headers:{'content-type':'application/json','x-neramit-device':getOrCreateDeviceToken()},body:JSON.stringify({draftId,requestId,variantCount:settings.variantCount})});const x=await r.json();if(!r.ok)throw new Error(x.error||'สร้างพรอมต์ไม่สำเร็จ');sessionStorage.setItem(`neramit_result_${draftId}`,JSON.stringify(x.result||x.job?.result||{}));router.push(`/result?draft=${draftId}`);}catch(e){setError(e instanceof Error?e.message:'สร้างพรอมต์ไม่สำเร็จ');setBusy(false);}}
  if(!data?.draft)return <div className="reviewSkeleton"><SkeletonBlock/><SkeletonBlock/><SkeletonBlock/></div>;
  const rows=briefRows(data.draft.brief);const posterText=String(data.draft.brief.poster_text||'ยังไม่ได้ระบุข้อความ');
  return <><div className="reviewWorkspace"><section className="reviewDetails"><div className="reviewSection"><div className="sectionHeading"><h2><NeramitIcon name="document" size={20}/>รายละเอียดงาน</h2><button className="textButton iconTextButton" onClick={()=>router.push(`/form?draft=${draftId}`)}><NeramitIcon name="edit" size={16}/>แก้ไข</button></div><div className="reviewRows">{rows.filter(([l])=>!['ข้อความบนโปสเตอร์','แพลตฟอร์ม','ภาษาพรอมต์','จำนวนรูปแบบ'].includes(l)).map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></div><div className="reviewSection"><div className="sectionHeading"><h2><NeramitIcon name="document" size={20}/>ข้อความบนโปสเตอร์</h2><span className="lockBadge"><NeramitIcon name="lock" size={15}/>คงข้อความเดิม</span></div><blockquote>{posterText}</blockquote></div><div className="reviewSection"><div className="sectionHeading"><h2><NeramitIcon name="image" size={20}/>ภาพอ้างอิง {data.references?.length??0} ภาพ</h2><button className="textButton iconTextButton" onClick={()=>router.push(`/references?draft=${draftId}`)}><NeramitIcon name="edit" size={16}/>แก้ไข</button></div><div className="miniRefs">{(data.references||[]).map((r,i)=><div key={r.id}><NeramitIcon name="image" size={26}/><small>ภาพ {i+1}</small></div>)}{!data.references?.length&&<p className="mutedText">ไม่ได้ใช้ภาพอ้างอิง</p>}</div></div></section><aside className="generationPanel"><h2><NeramitIcon name="settings" size={21}/>ตั้งค่าผลลัพธ์</h2><CreationSettingsControls value={settings} onChange={changeSettings}/><div className="readyCard"><NeramitIcon name="spark" size={25}/><strong>พร้อมเปลี่ยนไอเดีย<br/>เป็นพรอมต์แล้ว!</strong></div><div className="quotaCost"><b>งานนี้ใช้ 1 ครั้ง</b><span>สร้างสำเร็จแล้วจะเหลือโควตาตามระบบ</span></div><button className="gradientButton fullButton" onClick={generate} disabled={busy}><NeramitIcon name="spark" size={18}/>สร้างพรอมต์ {settings.variantCount} แบบ <NeramitIcon name="chevronRight" size={18}/></button><button className="btn fullButton" onClick={()=>router.push(`/form?draft=${draftId}`)}><NeramitIcon name="chevronLeft" size={18}/>กลับไปแก้ไข</button></aside></div>{busy&&<LoadingOverlay title="เนรมิตกำลังสร้างพรอมต์" detail="กำลังเรียบเรียงรายละเอียดให้พร้อมใช้กับ AI"/>}{error&&<Toast message={error} tone="error"/>}</>;
}
